//Code auto generated by [USER-NAME]
namespace YourNameSpace{

public class {{name}} {
				        
		        {{#fields}}
		           public {{type}} {{name}} {get;set;}  
		        {{/fields}}
				         
	}
}